import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import { SyncIndicator } from '@/components/SyncIndicator';

// Define fonts using the correct local path to the fonts directory
const geistSans = localFont({
  src: './fonts/GeistVF.woff', // Relative path to fonts directory from layout.tsx
  variable: '--font-geist-sans',
  display: 'swap', // Add this property to help with FOUT (Flash of Unstyled Text)
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff', // Relative path to fonts directory from layout.tsx
  variable: '--font-geist-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <Toaster />
        <SyncIndicator />
      </body>
    </html>
  );
}
